# Generated by Django 3.0.4 on 2020-04-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200419_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('padre', 'Padre'), ('hermano', 'Hermano/a'), ('madre', 'Madre'), ('hijo', 'Hijo/a'), ('esposo', 'Esposo/a')], max_length=50, null=True),
        ),
    ]
