# Generated by Django 3.0.4 on 2020-04-19 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200419_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(default=django.utils.timezone.now, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
