# Generated by Django 3.0.4 on 2020-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200419_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Persona'),
        ),
    ]
